### PR TITLE
Add links for workshop + useful links

### PR DESCRIPTION
**Pull request by RobbieZhuang**
**Note:** package-lock was also updated with `npm update`

video

### CODE REVIEW

**Comment by jenniferwills** [comment]
Can you use a different image for the video? I would expect a document of some kind if i clicked on it.

**Review by jenniferwills — APPROVED** [review]
❤️ 🎉 
looks great, thanks!

**Review by alexgirard — APPROVED** [review]
Looks good!

**Review by yingninggui — APPROVED** [review]
lgtm!

**Pull request merged**
