### PR TITLE
Update B-Soc Team for 2021

### PR DESCRIPTION
**Pull request by RobbieZhuang**
Added new photo of Atif and cleaned up about page.

### CODE REVIEW

**Review by alexgirard — APPROVED** [review]
👍  looks like its a draft pr currently, will need to switch to regular to merge in

**Comment by jenniferwills** [comment]
Excited to see what you all get up to in the future! :rocket: Have fun!! :tada:

**Comment by roxelo** [comment]
Is this good to merge now?

**Comment by RobbieZhuang** [comment]
@roxelo Live on sesoc.uwaterloo.ca!

**Pull request merged**
